# name: Release

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Install pnpm
#         uses: pnpm/action-setup@v2.0.1
#         with:
#           version: 6.15.1

#       - name: Set node version to v16
#         uses: actions/setup-node@v2
#         with:
#           node-version: 16.x
#           cache: "pnpm"
    
#       - run: npx conventional-github-releaser -p angular
#         env:
#           CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
